defaultMusicFolder = 'music'
defaultWallpaper = ''
defaultAlbumCover = 'images\cover.png'
defaultFont = 'Noto Sans'
defaultTitleFontSize = '12pt'
defaultFontSize = '11pt'
defaultTimeFontSize = '10pt'
defaultFileTitleFontSize = '14pt'
defaultFullTitleFont = f"font: {defaultTitleFontSize} \"{defaultFont}\";\n"
defaultFullFont = f"font: {defaultFontSize} \"{defaultFont}\";\n"
defaultFullTimeFont = f"font: {defaultTimeFontSize} \"{defaultFont}\";\n"
defaultFullFileTitleFont = f"font: {defaultFileTitleFontSize} \"{defaultFont}\";\n"
beginning = '00:00'